Algoritmo EJERCICIO_COSTO_DE_IMPRESION
	
	DEFINIR COSTO_DE_IMPRESION, COSTO_TOTAL Como Real
	Definir PAGINA Como Entero
	
	ESCRIBIR " INDIQUE EL NUMERO DE PAGINAS A IMPRIMIR: "
	LEER PAGINA
	
	ESCRIBIR "PRECIO POR PAGINA"
	LEER COSTO_DE_IMPRESION
	
	COSTO_TOTAL<- (COSTO_DE_IMPRESION*PAGINA)
	escribir "EL COSTO DE IMPRESION POR PAGINA ES: " COSTO_TOTAL "PESOS" 
	
FinAlgoritmo
