Algoritmo TIEMPO_DE_VIAJE
	
	DEFINIR TRAMO1, TRAMO2, TRAMO3, TIEMPO_TOTAL Como Real
	
	Escribir "INDIQUE EL TIEMPO PARCIAL EN EL PRIMER TRAMO: (HORAS) "
	LEER TRAMO1
	
    Escribir "INDIQUE EL TIEMPO PARCIAL EN EL SEGUNDO TRAMO: (HORAS)"
	LEER TRAMO2
	
	Escribir "INDIQUE EL TIEMPO PARCIAL EN EL TERCER TRAMO: (HORAS)"
	LEER TRAMO3
	
	TIEMPO_TOTAL<- (TRAMO1+TRAMO2+TRAMO3)
	Escribir "EL TIEMPO TOTAL DEL VIAJE ES DE: " TIEMPO_TOTAL  " HORAS"
	
FinAlgoritmo
